# -*- coding: utf-8 -*-
"""caLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UvXPlMPlVSdlHrJv6UWjKLxtDmSzSBO
"""

import os
import math

class Calculator:
    def __init__(self):
        self.history = []
        self.operations = {
            '1': {'name': 'Сложение', 'func': self.add},
            '2': {'name': 'Вычитание', 'func': self.subtract},
            '3': {'name': 'Умножение', 'func': self.multiply},
            '4': {'name': 'Деление', 'func': self.divide},
            '5': {'name': 'Возведение в степень', 'func': self.power},
            '6': {'name': 'Остаток от деления', 'func': self.modulo},
            '7': {'name': 'Целочисленное деление', 'func': self.floor_division}
        }

    def display_menu(self):
        """Отображение главного меню"""
        print("\n" + "="*50)
        print("🧮 КОНСОЛЬНЫЙ КАЛЬКУЛЯТОР")
        print("="*50)
        print("Математические операции:")
        for key, value in self.operations.items():
            print(f"  {key}. {value['name']}")
        print("\nДополнительные функции:")
        print("  8. 📋 Просмотреть историю операций")
        print("  9. 🗑️ Очистить историю")
        print("  0. ❌ Выход")
        print("="*50)

    def get_number_input(self, prompt):
        """Получение числового ввода от пользователя с обработкой ошибок"""
        while True:
            try:
                return float(input(prompt))
            except ValueError:
                print("❌ Ошибка: Введите корректное число!")

    def get_menu_choice(self):
        """Получение выбора пункта меню"""
        while True:
            choice = input("\nВыберите пункт меню (0-9): ").strip()
            if choice in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
                return choice
            else:
                print("❌ Ошибка: Выберите пункт от 0 до 9!")

    def add_to_history(self, operation, num1, num2, result):
        """Добавление операции в историю"""
        history_entry = f"{num1} {operation} {num2} = {result}"
        self.history.append(history_entry)
        return history_entry

    # Математические операции
    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):
        if b == 0:
            raise ZeroDivisionError("Деление на ноль!")
        return a / b

    def power(self, a, b):
        return a ** b

    def modulo(self, a, b):
        if b == 0:
            raise ZeroDivisionError("Деление на ноль!")
        return a % b

    def floor_division(self, a, b):
        if b == 0:
            raise ZeroDivisionError("Деление на ноль!")
        return a // b

    def perform_operation(self, choice):
        """Выполнение математической операции"""
        operation_info = self.operations[choice]
        operation_name = operation_info['name']
        operation_func = operation_info['func']

        print(f"\n--- {operation_name} ---")
        num1 = self.get_number_input("Введите первое число: ")
        num2 = self.get_number_input("Введите второе число: ")

        try:
            result = operation_func(num1, num2)

            # Определяем символ операции для истории
            operation_symbols = {
                '1': '+', '2': '-', '3': '*', '4': '/',
                '5': '^', '6': '%', '7': '//'
            }

            history_entry = self.add_to_history(
                operation_symbols[choice], num1, num2, result
            )

            print(f"✅ Результат: {history_entry}")

        except ZeroDivisionError as e:
            print(f"❌ Ошибка: {e}")
        except Exception as e:
            print(f"❌ Неожиданная ошибка: {e}")

    def show_history(self):
        """Показать историю операций"""
        print("\n" + "="*50)
        print("📋 ИСТОРИЯ ОПЕРАЦИЙ")
        print("="*50)

        if not self.history:
            print("История операций пуста")
        else:
            for i, entry in enumerate(self.history, 1):
                print(f"{i}. {entry}")

        print(f"\nВсего операций: {len(self.history)}")
        print("="*50)

    def clear_history(self):
        """Очистить историю операций"""
        self.history.clear()
        print("✅ История операций очищена!")

    def run(self):
        """Основной цикл программы"""
        print("Добро пожаловать в консольный калькулятор!")

        while True:
            self.display_menu()
            choice = self.get_menu_choice()

            if choice == '0':
                print("\n👋 До свидания! Спасибо за использование калькулятора!")
                break
            elif choice in ['1', '2', '3', '4', '5', '6', '7']:
                self.perform_operation(choice)
            elif choice == '8':
                self.show_history()
            elif choice == '9':
                self.clear_history()

            # Пауза перед следующим действием
            if choice != '0':
                input("\nНажмите Enter для продолжения...")

def main():
    """Основная функция"""
    calculator = Calculator()
    calculator.run()

if __name__ == "__main__":
    main()